server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/library?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 200
      max-wait-millis: 200

  thymeleaf:
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false

#  热部署
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#      exclude: WEB-INF/**

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志
logging:
  level:
    com.**: debug
